### ISSUE TITLE
Missing test_setup.py

### ISSUE THREAD

**Issue by toenuff** [Morgan-Stanley/treadmill#6]
test_setup.py is needed by nosetests - this is the script that loads the lib paths and tests paths that are located in /lib and /tests.

**Comment by toenuff** [comment]
FYI, the fix adds a test_setup.py and tests work, but it is likely not what is in Morgan Stanley and their may be a file conflict with internal/external code.  If this is not the best way to fix, let me know how it should be addressed.

**Comment by ceache** [comment]
The `standard_setup` branch will take care of this in a proper way
